# Generated by Django 5.0.1 on 2025-12-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetails',
            name='creditors_payment_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='debtors_payment_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='purchase_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='sale_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
