# Generated by Django 5.0.1 on 2025-12-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_businessdetails_creditors_payment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitydetails',
            name='end_use',
            field=models.CharField(choices=[('Home Loan', 'Home Loan'), ('Construction Loan', 'Construction Loan'), ('Business Expansion', 'Business Expansion'), ('Other', 'Other')], max_length=50),
        ),
    ]
